### ISSUE TITLE
Unable to be used while other keys held down

### ISSUE THREAD

**Issue by Llamalland** [keyboardio/Kaleidoscope-Redial#1] opened 2018-04-30 00:21 UTC
Anyone who types fast enough or holds keys down long enough for them to overlap will be unable to use redial while that is happening. In case it isn't already so, the action updating which is the key to be redialed needs to be a downstroke and not an upstroke.

**Comment by algernon** [comment] 2018-04-30 06:57
The plugin will decide which key to remember when that key is pressed (iow, on downstroke). When processing the Redial key, it will always simulate the remembered key, no matter the key state.

I'll try to reproduce to better observe the erroneous behaviour.

**Comment by Llamalland** [comment] 2018-07-17 09:08
Heya, any progress on this? Need anything from me to help reproduce this? For clarification, it isn't that redial is updating on upstroke instead of downstroke (I was just checking this because this issue brought the possibility to mind), just that redial itself doesn't work while another key is held down.

I'm almost at the stage where I could incorporate this into my typing technique, so I'm keen to have this work properly soon.

**Comment by algernon** [comment] 2018-07-25 06:44
No progress yet, sorry. I've been caught up with a host of other tasks. Will try to find some time to have another look at this too.

**Comment by Llamalland** [comment] 2018-07-26 05:16
No worries, keep up the good work :)

**Comment by algernon** [comment] 2018-10-18 05:43
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#396.

**Closed** 2018-10-18 05:44 UTC
Labels: bug
